language: node_js
sudo: required
node_js:
- '8'
install:
- npm install
- npm install -g mocha
scripts:
- npm test
branches:
  only:
  - lab-1
  - master
deploy:
  provider: heroku
  api_key:
    secure: C0LqSmqGPeICBrdjN6Ujv+Xl6WLGHf9SIpmCcmtlDo9IXfoXFACltC8PwPm0VdyTJxBdh1pxYxIejDNljCaIpXyiXanShLAWpeDivyl78llJKcGqMqBrMIy9ZRaxXuiFpo9kRamqesuBQbOPxv9UzCq3aIrIzyy0UeJJzrLbJcYZt2mPqvoauzoWZEKjwcv8854ntz+FYZaEEb06+QCBhnIOQyaMJw04klkhXhBfVnpS9Yc8MWxhgcF704FHqLpRB/gEaVCSIvNwQ4he7lnEQm+D4W1/Bz5OvSJ/wsCOLy3H2kykVSPHZ6pxQf97d+mrAsfIGugApchkZt9fmgXCvN+Xwh8qrHNnxn9X+j5QlKcLY7yXdyVAOJ6pO75E9ty+UOyfvlIGL8S+wil9Pn0+tc93WK9sRn6XTGt/GvdsPoq6RuF/dDobyhIOvNvPpuD3Z/t2FWozaVjjTv3wdfrx5GqPaYB3QD3v9p8NmSgDpNgMH5nq1kWpTeeaDehpVosNC5aPN841ufKXmPRCHxE8dQCAehsjXg/atbpfRQCoLW0NWacVZwVq40Qrrat9CcY7+cgup9J+USBon8TLCpxEwdqo931+AlnsfZ1dAf7qR83GzTAzlFi5j/LiHrB0xWzSMNgFd6U3GJJYXyKorHJrTnyN8kCYsSs681qtYYXfkWc=
  app: rsoi-course
  on:
    repo: sergkukuev/RSOI-course
    branch: master
  strategy: git
  api_key:
    secure: NXBYmpFSfC957Yqzgp2UGh3aHFUIM19VVVG1caY9+FKHWGOH02TFr34KVaIgIZwy0WQ74tAR7QyksC1O4h4djhF9DNHmraKQTMpJE+OYWQe94INij5wZsryKLilfiZQquFVc3Mbcs2qX21AwCIiakYWQ8q8mxHY3fOVse6FAReSBa1KqoU6sDwViajSOQa3eU0qWlYYZZRqBU+tpmQmmUqyTljPwvhvTsF0zhvAKdt+NctHaalwcvH4iLCplTztwDCSZxRVU1+v3Fh1IbMKMb3o7PDJHlcHMCJtrXYt+OPGd3DJx/HKGd7mSICVJcx/QB+psQhr1BI/MuqWwaaam9Z3Nu4qERkubix+fCZtUnubGqQuWmB0xCGJra+Ol0ciSt+GemoXS73EK77HHo9FBbYLxNBQ/uf8ks9Z24b+eM2HwSQZj0w+cniCaX51N+494PzKNgekLq9mD8Miwn/K7f8Om+YCZkwW/WQBXe62IusbVUqTY3jc0FGYDqTyEMnK+P3FLDOwquTHIAY4Y0bkB1FXbK/RtlHEMJvqIiND2S0V7GgJ0s6ksDVuEuh0w9kkLsHrMhE+iByISFDy9OM5PGtFxoBIPqdY7pAozDWNrt6EboWa72SmWFDkfX7cjS8a8i45UYxaMm3eO+n1OiloW10RqSuQO9sXRMBA2YxOEIYg=
